spring.application.name=gateway-service
server.port=8080
spring.profiles.active=true

#eureka.client.healthcheck.enabled=true
eureka.client.service-url.defaultZone=${EUREKA_URI:http://eureka:Admin%40123@localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.discovery.locator.enabled=true

spring.cloud.gateway.routes[0].id=identity-service
spring.cloud.gateway.routes[0].uri=http://localhost:8090/identity
spring.cloud.gateway.routes[0].predicates[0]=Path=/identity/**

spring.cloud.gateway.routes[1].id=catalog-service
spring.cloud.gateway.routes[1].uri=http://localhost:8091/catalog
spring.cloud.gateway.routes[1].predicates[0]=Path=/catalog/**

app.logging.filter.enabled=true
app.authentication.enabled=true
app.jwt.secret=1234567890abcdefghijklmnopqrstuvwxyz
