server:
  port: 8091
  servlet:
    context-path: /mail

spring:
  application:
    name: mail-service

  messages:
    basename: messages
    encoding: UTF-8

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            enable: true
            required: true
        smtps:
          timeout: 5000

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mail-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
